helm/kyverno/values.yaml

By default, kyverno deploys some `ClusterPolicy` resources for standard checks. We will manage policies separately, so don't deploy them as they override our policies

Do not deploy standard kyverno policies

---

CHANGELOG.md
helm/kyverno/templates/networkpolicy.yaml

Towards https://github.com/giantswarm/giantswarm/issues/18354
Kyverno exposes metrics on port 8000, where the `kyverno-svc-metrics` service routes traffic

Allow port 8000 for use by kyverno-svc-metrics

---

CHANGELOG.md
helm/kyverno/Chart.yaml
helm/kyverno/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/20446
enabling monitoring makes assumptions in the underlying charts that the Prometheus CRD for ServiceMonitors is installed and the namespace exists. This PR disables monitoring by default. I enable it for our MCs in `config`

Disable monitoring by default

---

helm/kyverno/Chart.yaml

Missed this in the update. Image version is correct, but app version is reported incorrectly

Bump AppVersion to 1.6.2

---

CHANGELOG.md
helm/kyverno/values.yaml

This PR does three things:
- sets the PriorityClass to `giantswarm-critical` which exists in both MCs and WCs
- sets the flag introduced in https://github.com/kyverno/kyverno/pull/4148 to limit the maximum number of ReportChangeRequests (RCRs) to 100*
- sets the `splitPolicyReport` flag to split reports more granularly, since some are too large to fit in `etcd` and without this flag set, the RCR limiting seems not to function as reliably.
*note: in testing this PR, the flag does not seem to provide completely bulletproof protection. For reasons I don't understand yet, the limit can be surpassed, and I've not been able to reproduce the throttling behavior for larger values (e.g. 500 or 1000). I'm setting to 100 in this PR out of an abundance of caution. The value can be overridden by users …

Improve Kyverno resilience (set RCR limit and PriorityClass)

---

CHANGELOG.md
helm/kyverno/values.yaml

From suggestions in https://github.com/giantswarm/giantswarm/issues/22650, raises the rate limit for the Kubernetes client used by Kyverno internally so that it will not limit itself as heavily.

Increase max QPS and burst rate limits

---

.circleci/config.yml
CHANGELOG.md

Also changes the collection pushes to depend on the control-plane catalog, since that's where MCs will be expecting these charts

Push to GCP collection

---

CHANGELOG.md
helm/kyverno/templates/_helpers.tpl

kyverno is failing because the `ServiceAccount` is missing. My guess is that after the job has failed for some reason, some of the resources are deleted, and the job will fail when retrying. I think we need to keep resources around when the job fails, because that way we can investigate what happened.
```
Type     Reason        Age                   From            Message
----     ------        ----                  ----            -------
Warning  FailedCreate  60s (x51 over 4h35m)  job-controller  Error creating: pods "kyverno-crd-install-" is forbidden: error looking up service account kyverno/kyverno-crd-install: serviceaccount "kyverno-crd-install" not found
```

Don't remove the 'crd-install' job when the job fails, so that we can investigate

---

CHANGELOG.md
helm/kyverno/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/26389
Updates `exceptionNamespace` list to set the `namespace` where `PolicyException` must be permitted.

Updates exceptionNamespace args for policyexceptions

---

CHANGELOG.md
helm/kyverno/templates/core-policies/chart-operator-polex.yaml
helm/kyverno/values.yaml

As long as we use `chart-operator` to deploy Apps, Kyverno can't possibly exist before it. This means `chart-operator` can't ship its own exception, and if chart-operator gets rejected then no other apps containing future exceptions can deploy. So we include the exception here.

Include PolicyException for chart-operator

---

CHANGELOG.md
helm/kyverno/templates/core-policies/restrict-polex-namespaces.yaml
helm/kyverno/templates/core-policies/restrict-policy-kind-wildcards.yaml
helm/kyverno/values.yaml

If a Policy or ClusterPolicy matches all resource kinds (`"*"`), it almost certainly matches more than intended. This also sends tons of unnecessary resources through kyverno admission review, which is bad for kyverno and bad for the cluster.
This policy forbids using wildcards in a Policy or ClusterPolicy match.

Create policy to forbid wildcards in policy match statements

---

CHANGELOG.md
helm/kyverno/templates/core-policies/restrict-polex-namespaces.yaml

Allow PolicyExceptions to exist in `flux-giantswarm` namespace as well.

Allow PolicyExceptions in flux-giantswarm namespace

---

CHANGELOG.md
helm/kyverno/templates/core-policies/chart-operator-polex.yaml
helm/kyverno/templates/crd-install/crd-psp.yaml
helm/kyverno/templates/kyverno-psp/kyverno-psp-rbac.yaml
helm/kyverno/templates/policyreporter-psp/policyreporter-psp-rbac.yaml
helm/kyverno/values.schema.json
helm/kyverno/values.yaml

Excempts the chart-operator service accounts from the restrict-polex-namespaces policy.

Add chart-operator ServiceAccount exception for PolEx creation

---

CHANGELOG.md
helm/kyverno/templates/core-policies/azure-cloud-node-manager-polex.yaml
helm/kyverno/values.schema.json
helm/kyverno/values.yaml

We have a circular dependency in CAPZ now. `azure-cloud-node-manager-app` depends on `kyverno` because of PolicyExceptions. `kyverno` depends on `chart-operator`, which depends on `Cilium` and `azure-cloud-node-manager-app` because of taints.  We decided to add core policies to kyverno app. See https://github.com/giantswarm/azure-cloud-node-manager-app/pull/46
Here is the discussion about where to add the exceptions.  https://gigantic.slack.com/archives/C02FL4EAADD/p1701181092993249?thread_ts=1696497100.521439&cid=C02FL4EAADD

Add PolicyException for Azure cloud node manager

---

CHANGELOG.md
helm/kyverno/templates/_helpers.tpl
helm/kyverno/templates/crd-install/crd-job.yaml
helm/kyverno/templates/upgrade-job/upgrade-job.yaml
helm/kyverno/values.yaml

Towards: https://github.com/giantswarm/giantswarm/issues/29184
This PR adds the missing labels to all the pods.
We will fix the CiliumNetworkPolicies in another pr.

Add missing component labels to all pods

---

CHANGELOG.md
helm/kyverno/templates/kyverno-cilium/ciliumnetworkpolicy.yaml
helm/kyverno/values.yaml

for kyverno-admission-controller, kyverno-plugin, kyverno-policy-reporter, kyverno-background-controller and kyverno-reports-controller
Without them, the Kyverno doesn't work well in the locked environments. Example: https://tekton.ci.giantswarm.io/#/namespaces/mc-bootstrap/pipelineruns/pr-mc-bootstrap-729-generate-mc4zfmt?pipelineTask=generate-mc&step=generate-mc
I tested this here: https://github.com/giantswarm/mc-bootstrap/pull/729 I was creating them in the mc-bootstrap to workaround this issue, but they logically belong to the app itself.

Add missing CiliumNetworkPolicies 

---

CHANGELOG.md
helm/kyverno/templates/kyverno-cilium/ciliumnetworkpolicy.yaml

towards https://github.com/giantswarm/giantswarm/issues/29581
fixes observed drop:
```
kyverno/kyverno-policy-reporter-99bd697d5-92xjr:44302 (ID:22023) <> kyverno/kyverno-ui-6f67595fdb-5sgt7:8080 (ID:45019) Policy denied DROPPED (TCP Flags: SYN)
```

Allow kyverno-policy-reporter to talk to kyverno-ui

---

.circleci/config.yml

CAPZ uses default-apps to install the security-bundle, which causes conflicts with collection. We shouldn't push to collection anymore.

Don't push to CAPZ collection

---

CHANGELOG.md
helm/kyverno/values.yaml

The upgrade job that downscales Kyverno was only needed for v1.10 upgrades. Now we can safely assume that nobody will run a v1.9 to v1.11 upgrade anymore.

Disable upgrade jobs for v1.10

---

helm/kyverno/templates/kyverno-cilium/ciliumnetworkpolicy.yaml

Disable the DNS proxying when rules are not specified. This was a recommendation from Cabagge.

Disable DNS Proxy when not needed

---

helm/kyverno/templates/core-policies/aws-cloud-controller-manager-polex.yaml
helm/kyverno/templates/core-policies/aws-ebs-csi-driver-polex.yaml
helm/kyverno/templates/core-policies/azure-cloud-controller-manager-polex.yaml
helm/kyverno/templates/core-policies/azure-cloud-node-manager-polex.yaml
helm/kyverno/templates/core-policies/chart-operator-polex.yaml
helm/kyverno/templates/core-policies/cilium-polex.yaml
helm/kyverno/templates/core-policies/cilium-policies-polex.yaml

We need to update the PolicyExceptions apiVersion to v2beta1 as v2alpha1 is being removed in the next Kyverno release.

Update PolicyExceptions to v2beta1

---

.circleci/config.yml
CHANGELOG.md
helm/kyverno/templates/core-policies/trivy-cluster-cleanup-policy.yaml
helm/kyverno/values.schema.json
helm/kyverno/values.yaml

This PR adds a Cleanup Policy to remove old Trivy Operator resources from the cluster.

Add extra Trivy Operator cleanup policy

---

CHANGELOG.md
helm/kyverno/charts/kyverno/templates/hooks/post-upgrade.yaml
helm/kyverno/charts/kyverno/templates/hooks/pre-delete.yaml

This has been an issue in some places because Helm doesn't remove the hook before trying to create it again.
It has been fixed upstream here: https://github.com/kyverno/kyverno/commit/2f4b8230304ff3de2001735791eb44ee1e69bedd , but this change will only make it on Kyverno v1.12.

Add `before-hook-creation` to upstream hooks

---

CHANGELOG.md
helm/kyverno/templates/_helpers.tpl

Towards: https://github.com/giantswarm/giantswarm/issues/30018
Adds the needed Helm annotations so these resources can be adopted by the chart in the future

Add Helm annotations to core policies

---

.github/workflows/sync-from-upstream.yaml

Towards: https://github.com/giantswarm/giantswarm/issues/31056
This PR allows to inherit the repository secrets to the update-chart workflow

Inherit secrets to update-chart workflow

---

CHANGELOG.md
helm/kyverno/templates/core-policies/cilium-agent-polex.yaml
helm/kyverno/templates/core-policies/cilium-hubble-polex.yaml
helm/kyverno/templates/core-policies/cilium-operator-polex.yaml

This PR split cilium polex per components and adds rule exceptions for the cilium-agent. Towards https://github.com/giantswarm/giantswarm/issues/31178
In the future, we'll remove the cilium-hubble polex and trim down the cilium-operator polex, as we solved several issues in the latest app version (https://github.com/giantswarm/giantswarm/issues/31475)

Split Cilium policy exceptions

---

helm/kyverno/templates/_helpers.tpl
helm/kyverno/templates/core-policies/aws-cloud-controller-manager-polex.yaml
helm/kyverno/templates/core-policies/aws-ebs-csi-driver-polex.yaml
helm/kyverno/templates/core-policies/azure-cloud-controller-manager-polex.yaml
helm/kyverno/templates/core-policies/azure-cloud-node-manager-polex.yaml
helm/kyverno/templates/core-policies/chart-operator-polex.yaml
helm/kyverno/templates/core-policies/cilium-agent-polex.yaml
helm/kyverno/templates/core-policies/cilium-hubble-polex.yaml
helm/kyverno/templates/core-policies/cilium-operator-polex.yaml
helm/kyverno/templates/core-policies/cilium-policies-polex.yaml
helm/kyverno/templates/core-policies/restrict-polex-namespaces.yaml
helm/kyverno/templates/core-policies/restrict-policy-kind-wildcards.yaml
helm/kyverno/templates/core-policies/restrict-policy-pod-contexts.yaml
helm/kyverno/templates/core-policies/trivy-cluster-cleanup-policy.yaml

Towards: https://github.com/giantswarm/giantswarm/issues/30018
This PR removes the Helm Hooks annotations from the core policies. This will need to be released after #412

Remove Helm hooks annotations from core policies

---

CHANGELOG.md
helm/kyverno/templates/core-policies/restrict-policy-kind-wildcards.yaml

Crossplane introduces types of `Policy` which are not related to kyverno but get blocked by the wildcard policy which then does not understand them.
To support crossplane co-existing, this change restricts the wildcard policy to the GVK for types Policy and ClusterPolicy

Policy wildcards should be restricted by GVK

---

helm/kyverno/Chart.yaml

We want to directly use the chart tags in Backstage catalog entities. This forbids spaces within a tag. This PR makes the tags compatible.

Update tags in chart
