giantswarm/kyverno-app

.circleci/config.yml

This PR:
- adds/changes/removes etc
Description on how kyverno can be tested.
Description of features to additionally test for kyverno installations.

Push all commits to test catalog

---

helm/kyverno/values.yaml

Older image

---

helm/kyverno/values.yaml

Bump memory limit

---

helm/kyverno/templates/networkpolicy.yaml

We want to add a networkpolicy to make sure there are no issues with traffic between webhooks

add networkpolicy

---

helm/kyverno/values.yaml

Can't run kyverno on test installations without this change.

Use GS quay for kyvernopre

---

.circleci/config.yml

Let's push kyverno on tag creation

push kyverno on tag

---

CHANGELOG.md
helm/kyverno/templates/NOTES.txt
helm/kyverno/templates/_helpers.tpl
helm/kyverno/templates/clusterrole.yaml
helm/kyverno/templates/clusterrolebinding.yaml
helm/kyverno/templates/configmap.yaml
helm/kyverno/templates/deployment.yaml
helm/kyverno/templates/policies/default/disallow-adding-capabilities.yaml
helm/kyverno/templates/policies/default/disallow-host-namespaces.yaml
helm/kyverno/templates/policies/default/disallow-host-path.yaml
helm/kyverno/templates/policies/default/disallow-host-ports.yaml
helm/kyverno/templates/policies/default/disallow-privileged-containers.yaml
helm/kyverno/templates/policies/default/disallow-proc-mount.yaml
helm/kyverno/templates/policies/default/disallow-selinux.yaml
helm/kyverno/templates/policies/default/restrict-apparmor-profiles.yaml
helm/kyverno/templates/policies/default/restrict-sysctls.yaml
helm/kyverno/templates/policies/restricted/deny-privilege-escalation.yaml
helm/kyverno/templates/policies/restricted/require-non-root-groups.yaml
helm/kyverno/templates/policies/restricted/require-run-as-nonroot.yaml
helm/kyverno/templates/policies/restricted/restrict-seccomp.yaml
helm/kyverno/templates/policies/restricted/restrict-volume-types.yaml
helm/kyverno/templates/secret.yaml
helm/kyverno/templates/service.yaml
helm/kyverno/templates/serviceaccount.yaml
helm/kyverno/values.yaml

Update chart to latest

---

CHANGELOG.md
helm/kyverno/values.yaml

It seems to just work from a quick test on giraffe. I will release and test with CAPI components in a follow up.

Enable high availability

---

CHANGELOG.md
helm/kyverno/values.yaml

I f-ed up and enabled these by accident.

Disable unneeded policies again

---

.circleci/config.yml
CHANGELOG.md

Adds kyverno to the production app catalog and pushes it to each app collection. This will deploy kyverno on all MCs once tagged

Push kyverno app to production app collections

---

.circleci/config.yml

Following announcement by Jose that the collection is not used.

Remove push to shared app-collection

---

CHANGELOG.md
helm/kyverno/Chart.yaml

Add config annotation

---

CHANGELOG.md
helm/kyverno/Chart.yaml
helm/kyverno/values.yaml

Update kyverno to v1.4.1

---

CHANGELOG.md
helm/kyverno/Chart.yaml

Add team annotation to chart.yaml

---

CHANGELOG.md
helm/kyverno/templates/servicemonitor.yaml

Towards https://github.com/giantswarm/giantswarm/issues/18354

Add ServiceMonitor for metrics Service

---

CHANGELOG.md
helm/kyverno/Chart.yaml
helm/kyverno/templates/vpa.yaml
helm/kyverno/values.yaml

Add VPA resource

---

CHANGELOG.md
helm/kyverno/values.yaml

Use Giant Swarm quay images

---

helm/kyverno/Chart.yaml

Towards https://github.com/giantswarm/giantswarm/issues/19663

Align team annotation with code owners

---

helm/kyverno/Chart.yaml

Towards https://github.com/giantswarm/giantswarm/issues/19663

Enrich app metadata in Chart.yaml

---

CHANGELOG.md
helm/kyverno/crds/crds.yaml
helm/kyverno/templates/crd-install/crd-job.yaml
helm/kyverno/templates/crd-install/crd-rbac.yaml

Cleanup transition code from CRD changes

---

helm/kyverno/values.yaml

Cleanup values.yaml in root chart

---

CHANGELOG.md
helm/kyverno/charts/kyverno/templates/poddisruptionbudget.yaml

make PDB version conditional based on available API

---

CHANGELOG.md
helm/kyverno/values.yaml

Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>

Enable PDB by default

---

CHANGELOG.md
helm/kyverno/values.yaml

Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>

Switch to using maxUnavailable

---

CHANGELOG.md
helm/kyverno/crds/crds.yaml

Update CRDS to the same version as the app

---

.circleci/config.yml
CHANGELOG.md

fix-push-to-collection

---

CHANGELOG.md
helm/kyverno/Chart.yaml
helm/kyverno/charts/kyverno/Chart.yaml
helm/kyverno/charts/kyverno/README.md
helm/kyverno/charts/kyverno/templates/crds.yaml
helm/kyverno/templates/crd-install/crd-job.yaml
helm/kyverno/templates/crd-install/crd-rbac.yaml

Towards https://github.com/giantswarm/giantswarm/issues/23700

Update kyverno 1.7.3

---

helm/kyverno/crd/crds.yaml

Update Kyverno CRDs for v1.7.3

---

.circleci/config.yml
CHANGELOG.md
helm/kyverno/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/22435 and https://github.com/giantswarm/giantswarm/issues/23971
Moves `kyverno` to its own namespace on Giant Swarm MCs. Does not affect the behavior of the app in workload clusters.

Use kyverno namespace

---

.ats/main.yaml
.circleci/config.yml
CHANGELOG.md
tests/ats/Pipfile
tests/ats/Pipfile.lock
tests/ats/test_basic_cluster.py

Towards https://github.com/giantswarm/giantswarm/issues/18865

Add ATS tests

---

.circleci/config.yml

Set namespace for GCP collection

---

.circleci/config.yml
CHANGELOG.md

push to cloud-director app collection

---

README.md

Update development docs for subtree update

---

CHANGELOG.md
helm/kyverno/Chart.yaml
helm/kyverno/charts/policy-reporter/Chart.lock
helm/kyverno/charts/policy-reporter/Chart.yaml
helm/kyverno/charts/policy-reporter/charts/ui/Chart.yaml
helm/kyverno/charts/policy-reporter/charts/ui/templates/deployment.yaml
helm/kyverno/charts/policy-reporter/values.yaml

Towards: https://gigantic.slack.com/archives/C02FL4EAADD/p1665753956628039

Update policy reporter

---

helm/kyverno/README.md

Towards https://github.com/giantswarm/kyverno-app/pull/181
The `helm/kyverno/README.md` file is a copy from upstream's `charts/kyverno/README.md` file and hasn't been updated in a while.
I think it's worth updating it as some of the values mentioned are not applicable anymore.

Update helm/kyverno chart docs

---

CHANGELOG.md

Revert failed release

---

CHANGELOG.md
helm/kyverno/templates/crd-install/crd-np.yaml

Towards: https://github.com/giantswarm/giantswarm/issues/24400

Add CiliumNetworkPolicy for CRD install job

---

helm/kyverno/charts/kyverno/Chart.yaml
helm/kyverno/charts/policy-reporter/Chart.yaml

Towards: https://github.com/giantswarm/giantswarm/issues/24606
Added team shield annotation to kyverno chart.yaml

Team annotation

---

CHANGELOG.md
helm/kyverno/Chart.yaml

Update changelog and Chart appVersion

---

CHANGELOG.md
helm/kyverno/values.schema.json
helm/kyverno/values.yaml

[WIP] Excludes kube-system namespace webhook

---

CHANGELOG.md
helm/kyverno/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/25046

Update Kyverno plugin resources

---

.github/workflows/sync-from-upstream.yaml
.github/workflows/zz_generated.update_chart.yaml

Test automation

---

.github/workflows/sync-from-upstream.yaml

Add precondition to update workflow

---

.github/workflows/zz_generated.update_chart.yaml

Update PR template

---

.github/workflows/sync-from-upstream.yaml

This PR adds automation to the CRDs migration we need to do on every update.
Here is an example commit:
https://github.com/giantswarm/kyverno-app/pull/212/commits/9686255e9b00925b1dc3e9aa790edaff34a8038b

Automate CRDs migration on update

---

CHANGELOG.md
helm/kyverno/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/24831

Adds annotation for kyverno service

---

.circleci/config.yml
CHANGELOG.md

Towards https://github.com/giantswarm/roadmap/issues/2189

Update circleci for collections

---

CHANGELOG.md
helm/kyverno/values.yaml

Set a default namespace for customer policy exceptions

---

CHANGELOG.md
helm/kyverno/templates/crd-install/crd-job.yaml

Towards: https://github.com/giantswarm/roadmap/issues/2389

Replace master with control-plane role on CRD install job

---

CHANGELOG.md
helm/kyverno/templates/_helpers.tpl
helm/kyverno/templates/hook-deletion/delete-job.yaml
helm/kyverno/templates/webhook-cleanup/delete-job.yaml
helm/kyverno/templates/webhook-cleanup/delete-rbac.yaml
helm/kyverno/templates/webhook-cleanup/delete-serviceaccount.yaml
helm/kyverno/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/26956

Add webhooks cleanup job

---

CHANGELOG.md
helm/kyverno/charts/kyverno/values.yaml

Related issue: https://github.com/giantswarm/giantswarm/issues/27202

Exclude chart-operator with resourceFilters

---

.circleci/config.yml
CHANGELOG.md

Add push to `capz-app-collection` on release

---

CHANGELOG.md
helm/kyverno/templates/core-policies/restrict-policy-pod-contexts.yaml
helm/kyverno/values.yaml

Closes https://github.com/giantswarm/giantswarm/issues/27193

Create core Policy to block Policies from using Pod-level context calls

---

.circleci/config.yml
CHANGELOG.md
helm/kyverno/templates/_helpers.tpl
helm/kyverno/values.yaml

Use feature gates instead of arguments and add UID for container

---

CHANGELOG.md
helm/kyverno/templates/vpa/vpa-admission-controller.yaml
helm/kyverno/templates/vpa/vpa-background-controller.yaml
helm/kyverno/templates/vpa/vpa-cleanup-controller.yaml
helm/kyverno/templates/vpa/vpa-kyverno-plugin.yaml
helm/kyverno/templates/vpa/vpa-kyverno-ui.yaml
helm/kyverno/templates/vpa/vpa-policy-reporter.yaml
helm/kyverno/templates/vpa/vpa-reports-controller.yaml
helm/kyverno/values.yaml

Removes CPU and capabilities check from VPA

Drop CPU from reports-controller VPA

---

.circleci/config.yml
renovate.json

Bumps architect-orb version to v4.32.0

Bump architect version

---

CHANGELOG.md
helm/kyverno/templates/crd-install/crd-job.yaml

Changed the crd-install job to use the  flag in its  command.

---

CHANGELOG.md
helm/kyverno/Chart.yaml

Reverts giantswarm/kyverno-app#309

Revert "Release v0.16.2"

---

CHANGELOG.md
helm/kyverno/templates/kyverno-cilium/ciliumnetworkpolicy.yaml

Fix endpoint selector

---

CHANGELOG.md
helm/kyverno/charts/kyverno/templates/hooks/post-upgrade.yaml
helm/kyverno/charts/kyverno/templates/hooks/pre-delete.yaml
helm/kyverno/templates/kyverno-cilium/ciliumnetworkpolicy.yaml

add ciliumnetworkpolicy for pre-delete and post-upgrade hooks

---

helm/kyverno/templates/crd-install/crd-job.yaml
helm/kyverno/templates/upgrade-job/upgrade-job.yaml
helm/kyverno/values.yaml

Add tags for all kubectl images so we don't use latest. Also increase PDB minAvailable setting to 2 for admission controller.

Update kubectl images and increase PDB minAvailable setting

---

CHANGELOG.md
helm/kyverno/templates/kyverno-cilium/ciliumnetworkpolicy.yaml
helm/kyverno/values.schema.json
helm/kyverno/values.yaml

This PRs add the possibility of adding extra settings to the Kyverno Admission Controller CNP.

Allow extra CNP settings for Kyverno Admission Controller

---

CHANGELOG.md
helm/kyverno/templates/kyverno-cilium/ciliumnetworkpolicy.yaml

Towards: https://gigantic.slack.com/archives/C02FL4EAADD/p1713279459382649 
Add DNS resolution for Kyverno Policy Reporter so it can connect to Kyverno UI.

Add needed DNS access for Kyverno Policy Reporter

---

.github/workflows/sync-from-upstream.yaml
CHANGELOG.md
helm/kyverno/crd/crd-0.yaml
helm/kyverno/crd/crd-1.yaml
helm/kyverno/crd/crd-10.yaml
helm/kyverno/crd/crd-11.yaml
helm/kyverno/crd/crd-2.yaml
helm/kyverno/crd/crd-3.yaml
helm/kyverno/crd/crd-4.yaml
helm/kyverno/crd/crd-5.yaml
helm/kyverno/crd/crd-6.yaml
helm/kyverno/crd/crd-7.yaml
helm/kyverno/crd/crd-8.yaml
helm/kyverno/crd/crd-9.yaml

Add necessary metadata for CRD adoption by kyverno-crds App.

Add necessary metadata for CRD adoption

---

CHANGELOG.md
helm/kyverno/templates/kyverno-cilium/ciliumnetworkpolicy.yaml

Fixes a templating issue in CiliumNetworkPolicy

Fix templating in CiliumNetworkPolicy DNS rules

---

CHANGELOG.md
helm/kyverno/templates/kyverno-cilium/ciliumnetworkpolicy.yaml

This key seems configured twice, which is wrong.

Remove duplicated key

---

CHANGELOG.md
helm/kyverno/values.yaml

Towards: https://github.com/giantswarm/giantswarm/issues/30018
Disables the CRD install Job in favor of the new `kyverno-crds` App.

Disable CRD install Job

---

CHANGELOG.md
helm/kyverno/templates/core-policies/restrict-polex-namespaces.yaml
helm/kyverno/templates/core-policies/restrict-policy-pod-contexts.yaml

Towards: https://gigantic.slack.com/archives/C02EVLE9W/p1733487016627449\?thread_ts\=1733486932.728749\&cid\=C02EVLE9W

Use GVK for core-policies kinds

---

CHANGELOG.md
helm/kyverno/values.schema.json
helm/kyverno/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/31174

Add runAsGroup to security context

---

CHANGELOG.md
helm/kyverno/.kube-linter.yaml
helm/kyverno/values.yaml

Add karpenter spot to node affinity for kyverno admission controller

---

CHANGELOG.md
helm/kyverno/templates/core-policies/aws-cloud-controller-manager-polex.yaml
helm/kyverno/templates/core-policies/aws-ebs-csi-driver-polex.yaml
helm/kyverno/templates/core-policies/azure-cloud-controller-manager-polex.yaml
helm/kyverno/templates/core-policies/azure-cloud-node-manager-polex.yaml
helm/kyverno/templates/core-policies/chart-operator-polex.yaml
helm/kyverno/templates/core-policies/cilium-agent-polex.yaml
helm/kyverno/templates/core-policies/cilium-hubble-polex.yaml
helm/kyverno/templates/core-policies/cilium-operator-polex.yaml
helm/kyverno/templates/core-policies/cilium-policies-polex.yaml
helm/kyverno/templates/core-policies/restrict-polex-namespaces.yaml

Updates PolicyExceptions to v2 in preparation to v2beta1 deprecation

Update PolicyExceptions apiVersions
